app:
  restart: always
  build: ./app
  expose:
    - "8000"
  env_file: .env
  command: bash -c "cd /usr/src && APP_SETTING=.env python -m app.server"

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  links:
    - app:app